export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOAD_PROFILE = 'LOAD_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'
export const LIKE_IMAGE = 'LIKE_IMAGE'
export const UNLIKE = 'UNLIKE'
export const REGISTER_ERROR = 'REGISTER_ERROR'